#!/bin/sh

# Print an introduction line in cyan
printf "\033[0;36mPre-commit hook is linting your changes for non-standard code...\033[0m \n"

# Grab feed of staged files 
files=$(git diff --name-only --cached)
numfiles=$( printf '%s' "$files" | grep -c '^' )

if [ $numfiles -eq 0 ]
then
  printf "\033[0;35mNo files staged. Nothing to check.\033[0m\n"
  exit 1
fi

# Default to zero which means the changes are good and the commit can go ahead
exitstatus=0

numnonpassingfiles=0

# Iterate over the filenames to discover the longest 
longest=0
for i in $files
do
  if [ ${#i} -gt $longest ]
  then
    longest=${#i}
  fi
done

# Iterate over the staged filenames
for i in $files
do
  # Print file name eg: "Checking: text.txt"
  printf "\033[0;35mChecking:\033[0m ${i} "

  # Print some padding spaces so the failed/success statuses line up
  padding=$(expr $longest - ${#i})
  for ((n=0;n<$padding;n++))
  do
    printf '%s' ' ' 
  done

  # Count number of lines with the plus symbol and tab characters at the start (eg. New lines, indented wrongly)
  tabbedlines=$( git diff --cached -U0 $i | egrep "^\+\t" )
  tabbedlinecount=$( printf '%s' "$tabbedlines" | grep -c '^' )

  # Count number of lines with the plus symbol and an odd number of spaces used to indent (eg. New lines, indented wrongly)
  oddspaceindents=$( git diff --cached -U0 $i | egrep "^\+(  )* {1}[^ ]+" )
  numoddspaceindents=$( printf '%s' "$oddspaceindents" | grep -c '^' )

  # Total up the offending lines 
  totalerrors=$((tabbedlinecount + numoddspaceindents))

  # Print the coloured [failed] or [success] report 
  if [ $totalerrors -gt 0 ]
  then
    printf "\033[0;31m[failed]\n"
    ((numnonpassingfiles++))
    exitstatus=1
  else
    printf "\033[0;32m[passed]\n"
  fi

  # Print report line about tab character being used
  if [ $tabbedlinecount -gt 0 ]
  then
    printf "${tabbedlinecount} lines indented with a tab character: \033[0;32m \n"
    for l in $tabbedlines
    do
      printf "$l \n"
    done
    printf "\n"
  fi

  # Print report line about indenting with an odd number of spaces 
  if [ $numoddspaceindents -gt 0 ]
  then
    printf "\033[0;31m${numoddspaceindents} lines indented using an odd number of spaces: \033[0;32m \n"
    for l in $oddspaceindents
    do
      printf "$l \n"
    done
    printf "\n"
  fi

  # Reset print color back to default for the next iteration
  printf "\033[0m"

done

# Print a summary of lint
if [ $exitstatus -eq 0 ]
then
  printf "\033[0;32m-- ${numfiles} file"
  if [ $numfiles -gt 1 ]
  then
    printf "s"
  fi
  printf " passed. Continuing with commit... \033[0m\n"
else
  printf '%s\n' "-- Sorry, ${numnonpassingfiles} of ${numfiles} staged files contain lines that do not pass."
fi

exit $exitstatus

